PREFIX dc10:  <http://purl.org/dc/elements/1.0/>
PREFIX dc11:  <http://purl.org/dc/elements/1.1/>

SELECT ?title ?author
WHERE  { ?y dc10:title ?x . 
{ ?book dc10:title  ?title ; dc10:author ?author } 
UNION 
{ ?book dc11:title  ?title ; dc11:author ?author } 
}