PREFIX :       <http://example/>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>

#this is a variant of a spec example
SELECT DISTINCT ?s
WHERE {
   ?s ?p ?o .
   MINUS {
      {?s foaf:givenName "Bob" .} UNION {?s foaf:givenName "Alice" .}
   }
}