CONSTRUCT {
    <http://data.linkedmdb.org/resource/actor/29539> <http://relationship.com/collab> ?act
}
WHERE {
    ?mov <http://data.linkedmdb.org/resource/movie/actor> <http://data.linkedmdb.org/resource/actor/29539> .
    ?mov <http://data.linkedmdb.org/resource/movie/actor> ?act .
    ?mov <http://data.linkedmdb.org/resource/movie/director> ?dir .
    ?dir <http://data.linkedmdb.org/resource/movie/director_name> ?x .
    ?y <http://data.linkedmdb.org/resource/movie/actor_name> ?x
} .

CONSTRUCT {
    <http://data.linkedmdb.org/resource/actor/29539> <http://relationship.com/collab> ?act2
}
WHERE {
    <http://data.linkedmdb.org/resource/actor/29539> <http://relationship.com/collab> ?act .
    ?mov <http://data.linkedmdb.org/resource/movie/actor> ?act .
    ?mov <http://data.linkedmdb.org/resource/movie/director> ?dir .
    ?dir <http://data.linkedmdb.org/resource/movie/director_name> ?x .
    ?y <http://data.linkedmdb.org/resource/movie/actor_name> ?x .
    ?mov <http://data.linkedmdb.org/resource/movie/actor> ?act2 .
} .