#-------------------------------------------------------
PREFIX : <http://example.org/gmark/>

SELECT * 
WHERE { 
	# works
	?x1 (:p16/^:p16)* ?x2
    # doesn't work
    # ?x0 (:p16/^:p16) ?x1 . ?x1 (:p16/^:p16)* ?x2 
}
#-------------------------------------------------------