PREFIX : <http://books.example/>

SELECT ?org (SUM(?lprice) AS ?totalPrice) (SUM(?lpages) AS ?totalPages)
WHERE {
  ?org :affiliates ?auth .
  ?auth :writesBook ?book .
  ?book :price ?lprice ; :nrPages ?lpages .
}
GROUP BY ?org